#!/usr/bin/env bash
#
# Install the Jenkins controller into the `cicd` namespace. Idempotent -
# `helm upgrade --install` either way.
#
# Run this on the lab host, not your workstation: it needs helm pointed at the
# minikube cluster.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "${SCRIPT_DIR}")"

NS="cicd"
JENKINS_CHART_VERSION="${JENKINS_CHART_VERSION:-5.9.63}"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mxx\033[0m %s\n' "$*" >&2; exit 1; }

command -v helm >/dev/null || die "helm not found"
kubectl cluster-info >/dev/null 2>&1 || die "kubectl cannot reach a cluster"

# The tailnet name comes from the Tailscale operator that scenario 01 installs.
if ! kubectl get ns tailscale >/dev/null 2>&1; then
  die "namespace 'tailscale' not found - run scenario 01 first"
fi

log "adding the jenkins helm repo"
helm repo add jenkins https://charts.jenkins.io >/dev/null 2>&1 || true
helm repo update jenkins >/dev/null

log "creating namespace ${NS}"
kubectl create namespace "$NS" --dry-run=client -o yaml | kubectl apply -f - >/dev/null

# First start downloads and installs the plugins, which takes a few minutes.
log "installing jenkins (chart ${JENKINS_CHART_VERSION})"
helm upgrade --install jenkins jenkins/jenkins \
  --namespace "$NS" \
  --version "$JENKINS_CHART_VERSION" \
  --values "${ROOT_DIR}/helm/jenkins.values.yaml" \
  --wait --timeout 15m

log "waiting for the controller"
kubectl -n "$NS" rollout status statefulset/jenkins --timeout=10m

cat <<EOF

Jenkins is installed.

From your workstation, over the tailnet (give the proxy a minute to register):
  http://jenkins:8080

Log in as admin. The password was generated by the chart:
  kubectl -n ${NS} get secret jenkins -o jsonpath='{.data.jenkins-admin-password}' | base64 -d; echo

EOF
